name: Run Postman Tests with Newman

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  newman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        npm install

    - name: Run Postman Collection with Newman
      run: |
        newman run postman/collection.json --environment postman/environment.json
